[project]
name = "tut-syllabus-json"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "selenium>=4.29.0",
    "tqdm>=4.67.1",
]
